server:
  port: 8081
spring:
  application:
    name: hazelcast
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true
      path: /h2
rate-limiting:
  enabled: true
